<?php
declare(strict_types=1); session_start();
spl_autoload_register(function(string $class): void { $prefix='ChezVous\\'; if(str_starts_with($class,$prefix)){ $file=dirname(__DIR__).'/src/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php'; if(is_file($file)) require $file; }});
use ChezVous\Config\Env; use ChezVous\Shared\Database\Connection; use ChezVous\Shared\Security\Csrf; use ChezVous\Shared\View\View; use ChezVous\Features\Events\EventRepository; use ChezVous\Features\Tasks\TaskRepository;
Env::load(dirname(__DIR__).'/.env'); $page=$_GET['page']??'dashboard'; $allowed=['dashboard'=>'Visão geral','events'=>'Eventos','production'=>'Produção','tasks'=>'Tarefas','agenda'=>'Agenda','processes'=>'Processos & Rotinas','meetings'=>'Reuniões','team'=>'Equipe','departments'=>'Departamentos']; if(!isset($allowed[$page])){$page='dashboard';http_response_code(404);} $db=Connection::make(); $eventsRepo=new EventRepository($db);$tasksRepo=new TaskRepository($db);
function redirect(string $page): never { header('Location: /?page='.$page); exit; }
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Csrf::verify($_POST['_csrf']??null)){http_response_code(419);exit('Solicitação inválida. Atualize a página e tente novamente.');}try{$action=$_POST['action']??'';if($action==='create_event'){$file=null;if(isset($_FILES['budget_file'])&&$_FILES['budget_file']['error']===UPLOAD_ERR_OK){$ext=strtolower(pathinfo($_FILES['budget_file']['name'],PATHINFO_EXTENSION));if(!in_array($ext,['pdf','jpg','jpeg','png'],true))throw new InvalidArgumentException('Arquivo deve ser PDF, JPG ou PNG.');$file=bin2hex(random_bytes(12)).'.'.$ext;move_uploaded_file($_FILES['budget_file']['tmp_name'],__DIR__.'/uploads/'.$file);} $eventsRepo->create(['client_name'=>trim($_POST['client_name']),'event_type'=>$_POST['event_type'],'event_date'=>$_POST['event_date'],'event_time'=>$_POST['event_time'],'venue'=>trim($_POST['venue']),'guest_count'=>(int)$_POST['guest_count'],'commercial_owner'=>trim($_POST['commercial_owner']),'amount'=>(float)str_replace(',','.',preg_replace('/[^0-9,]/','',$_POST['amount']??'0')),'budget_file'=>$file]);$_SESSION['flash']='Ordem de evento criada com sucesso.';redirect('events');}if($action==='create_task'){$tasksRepo->create(['title'=>trim($_POST['title']),'department_id'=>(int)$_POST['department_id'],'assignee_id'=>(int)$_POST['assignee_id'],'event_id'=>(int)$_POST['event_id'],'validator_name'=>trim($_POST['validator_name']),'priority'=>$_POST['priority'],'due_at'=>str_replace('T',' ',$_POST['due_at']).':00','description'=>trim($_POST['description'])]);$_SESSION['flash']='Tarefa criada e delegada.';redirect('tasks');}if($action==='toggle_task'){$tasksRepo->toggle((int)$_POST['task_id']);redirect($page);}if($action==='validate_task'){$tasksRepo->validate((int)$_POST['task_id']);redirect('tasks');}}catch(Throwable $e){$_SESSION['flash']='Não foi possível salvar: '.$e->getMessage();redirect($page);}}
$events=$eventsRepo->all();$tasks=$tasksRepo->all();$departments=$db->query('SELECT * FROM departments ORDER BY name')->fetchAll();$users=$db->query('SELECT u.*,d.name department FROM users u LEFT JOIN departments d ON d.id=u.department_id ORDER BY u.name')->fetchAll(); $flash=$_SESSION['flash']??null;unset($_SESSION['flash']);
require dirname(__DIR__).'/src/Features/Dashboard/Views/layout.php';
